- name: /win-phoronix/ check memory limit
  win_shell: "Get-Item WSMan:\\localhost\\Shell\\MaxMemoryPerShellMB"
  changed_when: false
  register: result

- name: /win-phoronix/ increase winrm memory limits
  win_shell: "Set-Item WSMan:\\localhost\\Shell\\MaxMemoryPerShellMB 3096"
  when: '"3096" not in result.stdout'

- name: /win-phoronix/ install php
  win_chocolatey:
    name: php
    state: present
    params:  "/InstallDir:{{ ansible_env.SystemDrive }}\\PHP"

- name: /win-phoronix/ enable php openssl
  win_lineinfile:
    line: 'extension=openssl'
    path: "{{ ansible_env.SystemDrive }}\\PHP\\php.ini"
    regex: ';?extension=openssl'

- name: /win-phoronix/ install cygwin
  win_chocolatey:
    name: cygwin
    state: present
    params:  "/InstallDir:{{ ansible_env.SystemDrive }}\\cygwin64"

# TODO this doesn't actually work
# look at https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.185-1/virtio-win-gt-x64.msi instead
- name: /win-phoronix/ install virtio drivers
  win_chocolatey:
    name: virtio-drivers
    state: present
