- include: dependencies.yml

- include: phoronix.yml

- include: ssh.yml

- name: /win-phoronix/ shutdown system
  win_shell: shutdown /s /f
  when: "winphoronix_shutdown is defined and winphoronix_shutdown"
